<Project>
  <PropertyGroup>
    <Version>0.4.1</Version>
    <Authors>TSCC_WASD contributors</Authors>
    <Product>TSCC_WASD</Product>
    <Description>Makes Xbox and NS2 Pro controllers appear as a DualShock 4 on Windows.</Description>
    <PackageLicenseExpression>MIT AND Zlib</PackageLicenseExpression>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
