<Project>
  <PropertyGroup>
    <Version>0.3.0</Version>
    <Authors>YnyrWASD contributors</Authors>
    <Product>YnyrWASD</Product>
    <Description>NS2 Pro USB and XInput to virtual DualShock 4 mapper for Windows.</Description>
    <PackageLicenseExpression>MIT AND Zlib</PackageLicenseExpression>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
